import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Fetch Layout");
  await new Promise((res) => setTimeout(res, 3000));
  console.log("Fetch Layout Finished");

  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Outer layout</h1>
        {children}
      </body>
    </html>
  );
}
